config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :conversations do
    resources :messages
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/user' => 'users#show'
  delete '/user' => 'users#destroy'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

end

app/models/application.rb
class Application < Rails::Application

  config.middleware.insert_before 0, Rack::Cors do
    allow do
      origins '*'
      resource '*', headers: :any, methods: [:get, :post, :options]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user1, :foreign_key => :user1_id, class_name: 'User'
  belongs_to :user2, :foreign_key => :user2_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :user1_id, :scope => :user2_id

  scope :between, -> (user1_id, user2_id) do
    where("(conversations.user1_id = ? AND conversations.user2_id = ?) OR (conversations.user1_id = ? AND conversations.user2_id = ?)", user1_id, user2_id, user2_id, user1_id)
  end

  # def encrypt_code_key
  #   self.code_key_salt = BCrypt::Engine.generate_salt
  #   self.code_key_hash = BCrypt::Engine.hash_secret(code_key, code_key_salt)
  # end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%l:%M %p")
  end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true
  before_save :encrypt_password


  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      return @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You need to sign in."
      redirect_to '/'
    end
  end

  def authorize_conversation(user, conversation)
    if current_user.id != conversation.user1_id && current_user.id != conversation.user2_id
      flash[:alert] = 'You are not authorized to access that feature.'
      redirect_to '/'
    end
  end

  def encode_message(message, key)
    if key > 26 || key < 1
      return 'I told you not to do that'
    end
    alphabet = ('a'..'z').to_a
    alphabet_slice_first = alphabet.slice(key..-1)
    alphabet_slice_last = alphabet.slice(0..(key-1))
    encoded_alphabet = alphabet_slice_first + alphabet_slice_last
    message_array = message.downcase.split('')
    coded_message_array = []
    message_array.each do |char|
      if alphabet.include?(char)
        new_char = encoded_alphabet[alphabet.find_index(char)]
        coded_message_array.push(new_char)
      else
        coded_message_array.push(char)
      end
    end
    encoded_message = coded_message_array.join
  end

  def decode_message(message, key)
    if key > 26 || key < 1
      return 'I told you not to do that'
    end
    alphabet = ('a'..'z').to_a
    alphabet_slice_first = alphabet.slice(key..-1)
    alphabet_slice_last = alphabet.slice(0..(key-1))
    encoded_alphabet = alphabet_slice_first + alphabet_slice_last
    encoded_message_array = message.split('')
    decoded_message_array = []
    encoded_message_array.each do |char|
      if encoded_alphabet.include?(char)
        new_char = alphabet[encoded_alphabet.find_index(char)]
        decoded_message_array.push(new_char)
      else
        decoded_message_array.push(char)
      end
    end
    decoded_message = decoded_message_array.join
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :authorize

  def index
    @user = User.find(session[:user_id])
    @users = User.all
    @conversations = Conversation.where("user1_id = ? OR user2_id = ?", @user.id, @user.id)
    render :index
  end

  def new
    @conversation = Conversation.new
    @authenticity_token = session[:_csrf_token]
  end

  def create
    if Conversation.between(params[:user1_id], params[:user2_id]).present?
      @code_key = conversation_params['code_key']
      @conversation = Conversation.between(params[:user1_id],
        params[:user2_id]).first
    else
      @conversation = Conversation.create!({'user1_id'=>conversation_params[:user1_id], 'user2_id'=>conversation_params[:user2_id]})
      @code_key = conversation_params['code_key']
    end
    redirect_to conversation_messages_path(@conversation, {:code_key => @code_key})
  end



  private

  def conversation_params
    params.permit(:user1_id, :user2_id, :code_key)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
    @user = User.find(session[:user_id])
    @conversations = Conversation.where("user1_id = ? OR user2_id = ?", @user.id, @user.id)
    @conversation = Conversation.find(params[:conversation_id])
    authorize_conversation(@user, @conversation)
    if !@code_key
      @code_key = params[:code_key]
    end
  end

  def index
    @messages = []
    @coded_messages = @conversation.messages
    @coded_messages.each do |message|
      @messages.push(decode_message(message.body, @code_key.to_i))
    end
    if current_user.id == @conversation.user1_id
      @other_user = User.find(@conversation.user2_id)
    else
      @other_user = User.find(@conversation.user1_id)
    end
    if @coded_messages.last
      if @coded_messages.last.user_id != current_user.id
        @coded_messages.each do |message|
          message.update({read: true})
        end
      end
    end
    @message = @conversation.messages.new
  end

  def create
    id = message_params['user_id']
    body = message_params['body']
    encoded_body = encode_message(body, @code_key.to_i)
    @message = @conversation.messages.new({"body"=>encoded_body, "user_id"=>id})
    if @message.save
      redirect_to conversation_messages_path(@conversation, {:code_key => @code_key})
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id, :read)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      reset_session
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      current_time = Time.new
      session[:updated_at] = current_time
      redirect_to "/conversations"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show, :destroy]

  def new
    @user = User.new
  end

  def create
    if @user = User.new(user_params)
      if @user.save
        flash[:notice] = "You've successfully signed up!"
        session[:user_id] = @user.id
        redirect_to "/conversations"
      else
        flash[:alert] = "There was a problem signing up."
        render :new
      end
    else
      flash[:alert] = "There was a problem signing up. Try clearing your cookies and trying again"
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
    render :show
  end

  def destroy
    @user = User.find(session[:user_id])
    @user.destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<div class='users'>

  <% if @conversations.length > 0 %>
    <h2 class='convo-header'>Your Conversations</h2>
    <% @conversations.each do |conversation| %>
      <% if conversation.user1_id == @user.id %>
        <% user2 = User.find(conversation.user2_id) %>
      <% elsif conversation.user2_id == @user.id %>
        <% user2 = User.find(conversation.user1_id) %>
      <% end %>
      <div class='user'>
        <p><span class='dot'><%= user2.username[0] %></span><%= link_to user2.username, new_conversation_path(user1_id: current_user.id, user2_id: user2.id) %></p>
      </div>
    <% end %>
  <% end %>

  <h2 class='convo-header'>All Users</h2>

  <% if @users %>
    <% @users.each do |user| %>
      <% if user.id != @user.id %>
        <div class='contact'>
          <p><span class='dot'><%= user.username[0] %></span><%= link_to user.username, new_conversation_path(user1_id: current_user.id, user2_id: user.id) %></p>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class='blank'>
</div>

app/views/conversations/new.html.erb
<div class='background-page'>
  <div class='all-forms'>
    <h2>Code Key</h2>
    <form action='/conversations' method='post'>
      <input type="hidden" name="authenticity_token" value="<%= @authenticity_token %>">
      <input type="hidden" name="user1_id" value="<%= params[:user1_id] %>">
      <input type="hidden" name="user2_id" value="<%= params[:user2_id] %>">
      <p><label for='code_key'>Enter your previously-agreed-upon key (a number between 1 and 26) for this conversation. Unless both of you enter the same key, you will not be able to read eachother's messages. If you enter a number greater than 26... just don't</label></p>
      <input type='text' name='code_key' id='code_key' class='form-item'>
      <p><input type='submit' name='commit' value='Go to chat' class='form-item' data-disable-with='set key'></p>
    </form>
  </div>
</div>

app/views/layouts/_contacts.html.erb
<% if @conversations %>
  <div class='contacts'>
    <% @conversations.each do |conversation| %>
      <% if conversation.user1_id == @user.id %>
        <% user2 = User.find(conversation.user2_id) %>
      <% elsif conversation.user2_id == @user.id %>
        <% user2 = User.find(conversation.user1_id) %>
      <% end %>
      <div class='user'>
        <p><span class='dot'><%= user2.username[0] %></span><%= link_to user2.username, conversation_messages_path(conversation) %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if @object %>
  <% if @object.errors.any? %>
    <p>Please fix these errors:</p>
      <% @object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
  <% end %>
<% end %>

app/views/layouts/_nav_bar.html.erb
<div class='navbar'>
  <% if current_user %>
    <span><%= link_to "Sign out", '/signout' %> |</span>
    <span><%= link_to "Show all users", '/conversations' %></span>
  <% else %>
    <span><%= link_to "Sign up", '/signup' %> |</span>
    <span><%= link_to "Sign in", '/' %></span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">

  </head>

  <body>

    <%= render "layouts/nav_bar" %>

    <%= flash[:notice] %>
    <%= flash[:alert] %>

    <%= yield %>

  </body>
</html>

app/views/messages/index.html.erb
<% if @conversations %>
  <div class='contacts'>
    <% @conversations.each do |conversation| %>
      <% if conversation.user1_id == @user.id %>
        <% user2 = User.find(conversation.user2_id) %>
      <% elsif conversation.user2_id == @user.id %>
        <% user2 = User.find(conversation.user1_id) %>
      <% end %>
      <% if user2.username == @other_user.username %>
        <% select_class = 'selected' %>
      <% else %>
        <% select_class = 'normal' %>
      <% end %>
      <div class='user <%= select_class %>'>
        <p><span class='dot'><%= user2.username[0] %></span><%= link_to user2.username, new_conversation_path(user1_id: current_user.id, user2_id: user2.id) %></p>
      </div>
    <% end %>
  </div>
<% end %>

<p id='message-top'>Messages to <%= @other_user.username %></p>

<div class='messages'>

  <div class='messages-scroll'>

    <% if @coded_messages %>
      <% @coded_messages.each_with_index do |message, index| %>
        <% if message.body %>
          <% user = User.find(message.user_id) %>
          <% if user.username == current_user.username %>
            <% identify_class = 'me' %>
          <% else %>
            <% identify_class = 'you' %>
          <% end %>
          <% if message.read %>
            <% read_class = 'is-read' %>
          <% else %>
            <% read_class = 'unread' %>
          <% end %>
          <div class="<%= identify_class %>">
            <p><%= @messages[index] %></p>
            <p class='timestamp'><%= message.message_time %><span class='read <%= read_class %>'></span></p>
          </div>
        <% end %>
      <% end %>
    <% end %>

  </div>

  <%= form_for [@conversation, @message] do |f| %>
    <p><%= f.text_field :body, placeholder: 'Send message' %><%= f.submit "", type: 'hidden' %></p>
    <p><%= f.text_field :user_id, value: current_user.id, type: "hidden" %></p>
    <input type="hidden" name="code_key" value="<%= @code_key %>">

  <% end %>

</div>

app/views/users/new.html.erb
<%= render "layouts/errors", :object => @user %>

<div class='background-page'>

  <div class='all-forms'>
    <h1> Sign up for Letterwheel</h1>
    <%= form_for @user do |f| %>
      <p><%= f.label "Email" %> address</p>
      <p><%= f.text_field :email, class: 'form-item' %></p>
      <p><%= f.label "Username" %></p>
      <p><%= f.text_field :username, class: 'form-item' %></p>
      <p><%= f.label "Password" %></p>
      <p><%= f.password_field :password, class: 'form-item' %></p>
      <p id='password-info'>Make sure your password is more than 8 characters long</p>
      <p><%= f.label :password_confirmation %></p>
      <p><%= f.password_field :password_confirmation, class: 'form-item' %></p>
      <p><%= f.submit "Sign Up", class: 'form-item', id: 'sign-button' %></p>
      <hr>
      <p>Or <span id='signup-link'><%= link_to "sign in", '/signin' %></span></p>
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<h1>Your Profile</h1>
<p>Name: <%= @user.username %></p>
<p>Email: <%= @user.email %></p>

<p><%= link_to "Delete your profile", user_path(@user),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>